/*
 * Copyright (c) 2026 PenEngineering S.R.L
 * SPDX-License-Identifier: Apache-2.0
 */

//go:build cgo

// Dilithium-2 (CRYSTALS-Dilithium / FIPS 204 ML-DSA-44) support via liboqs-go.
// Requires liboqs shared library installed on the build host.
// AkiraPlatform enterprise feature — opt-in via akira-cli --pqc flags.
package crypto

import (
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"os"

	"github.com/open-quantum-safe/liboqs-go/oqs"
)

const (
	dilithiumAlg     = "Dilithium2"
	dilithiumPrivPEM = "DILITHIUM2 PRIVATE KEY"
	dilithiumPubPEM  = "DILITHIUM2 PUBLIC KEY"
)

// GenerateDilithiumKeyPair generates a Dilithium-2 keypair.
// Returns (publicKey, privateKey, error). Both are raw byte slices.
func GenerateDilithiumKeyPair() (pub, priv []byte, err error) {
	var signer oqs.Signature
	defer signer.Clean()

	if err := signer.Init(dilithiumAlg, nil); err != nil {
		return nil, nil, fmt.Errorf("dilithium init: %w", err)
	}

	pub, err = signer.GenerateKeyPair()
	if err != nil {
		return nil, nil, fmt.Errorf("dilithium keygen: %w", err)
	}

	return pub, signer.ExportSecretKey(), nil
}

// WriteDilithiumPrivateKey writes a Dilithium-2 private key to path as PEM (mode 0600).
func WriteDilithiumPrivateKey(priv []byte, path string) error {
	data := pem.EncodeToMemory(&pem.Block{Type: dilithiumPrivPEM, Bytes: priv})
	return os.WriteFile(path, data, 0600)
}

// WriteDilithiumPublicKey writes a Dilithium-2 public key to path as PEM (mode 0644).
func WriteDilithiumPublicKey(pub []byte, path string) error {
	data := pem.EncodeToMemory(&pem.Block{Type: dilithiumPubPEM, Bytes: pub})
	return os.WriteFile(path, data, 0644)
}

// WriteDilithiumProvisionBundle writes pqc_provision.txt with the hex-encoded
// public key ready to paste into CONFIG_AKIRA_PLATFORM_PQC_PUBKEY in prj.conf.
func WriteDilithiumProvisionBundle(pub []byte, path string) error {
	hexKey := hex.EncodeToString(pub)
	content := fmt.Sprintf(
		"# AkiraPlatform PQC provisioning bundle — generated by akira-cli keygen --pqc\n"+
			"# Add the line below to your board's prj.conf (requires CONFIG_AKIRA_PLATFORM_PQC_SIGNING=y):\n"+
			"CONFIG_AKIRA_PLATFORM_PQC_PUBKEY=\"%s\"\n",
		hexKey,
	)
	return os.WriteFile(path, []byte(content), 0644)
}

// LoadDilithiumPrivateKey reads a Dilithium-2 private key from a PEM file.
func LoadDilithiumPrivateKey(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("%s: no PEM block found", path)
	}
	return block.Bytes, nil
}

// LoadDilithiumPublicKey reads a Dilithium-2 public key from a PEM file.
func LoadDilithiumPublicKey(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("%s: no PEM block found", path)
	}
	return block.Bytes, nil
}

// SignDilithium signs message with a Dilithium-2 private key and returns the signature.
func SignDilithium(priv, message []byte) ([]byte, error) {
	var signer oqs.Signature
	defer signer.Clean()

	if err := signer.Init(dilithiumAlg, priv); err != nil {
		return nil, fmt.Errorf("dilithium init: %w", err)
	}

	sig, err := signer.Sign(message)
	if err != nil {
		return nil, fmt.Errorf("dilithium sign: %w", err)
	}
	return sig, nil
}

// VerifyDilithium verifies a Dilithium-2 signature. Returns true if valid.
func VerifyDilithium(pub, message, signature []byte) bool {
	var verifier oqs.Signature
	defer verifier.Clean()

	if err := verifier.Init(dilithiumAlg, nil); err != nil {
		return false
	}

	valid, err := verifier.Verify(message, signature, pub)
	if err != nil {
		return false
	}
	return valid
}
