/*
 * Copyright (c) 2026 PenEngineering S.R.L
 * SPDX-License-Identifier: Apache-2.0
 */

// Package crypto provides Ed25519 key generation and PEM I/O helpers.
package crypto

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"os"
)

// GenerateKeyPair generates a fresh Ed25519 keypair.
func GenerateKeyPair() (ed25519.PublicKey, ed25519.PrivateKey, error) {
	return ed25519.GenerateKey(rand.Reader)
}

// WritePrivateKey writes priv to path as a PKCS#8 PEM file (mode 0600).
func WritePrivateKey(priv ed25519.PrivateKey, path string) error {
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return fmt.Errorf("marshal private key: %w", err)
	}
	data := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der})
	return os.WriteFile(path, data, 0600)
}

// WritePublicKey writes pub to path as a PKIX PEM file (mode 0644).
func WritePublicKey(pub ed25519.PublicKey, path string) error {
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return fmt.Errorf("marshal public key: %w", err)
	}
	data := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der})
	return os.WriteFile(path, data, 0644)
}

// WriteProvisionBundle writes a device_provision.txt containing the pubkey
// hex string ready to paste into CONFIG_AKIRA_APP_PUBKEY in prj.conf.
func WriteProvisionBundle(pub ed25519.PublicKey, path string) error {
	hexKey := hex.EncodeToString(pub)
	content := fmt.Sprintf(
		"# AkiraOS device provisioning bundle — generated by akira-cli keygen\n"+
			"# Add the line below to your board's prj.conf:\n"+
			"CONFIG_AKIRA_APP_PUBKEY=\"%s\"\n",
		hexKey,
	)
	return os.WriteFile(path, []byte(content), 0644)
}

// LoadPrivateKey reads a PKCS#8 PEM private key from path.
func LoadPrivateKey(path string) (ed25519.PrivateKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("%s: no PEM block found", path)
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse private key: %w", err)
	}
	priv, ok := key.(ed25519.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("%s: not an Ed25519 private key", path)
	}
	return priv, nil
}

// LoadPublicKey reads a PKIX PEM public key from path.
func LoadPublicKey(path string) (ed25519.PublicKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("%s: no PEM block found", path)
	}
	key, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse public key: %w", err)
	}
	pub, ok := key.(ed25519.PublicKey)
	if !ok {
		return nil, fmt.Errorf("%s: not an Ed25519 public key", path)
	}
	return pub, nil
}
